// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagementApi.Data;

#nullable disable

namespace ProjectManagementApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231231232928_pmDB")]
    partial class pmDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagementApi.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedAtDate")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineDate")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndedAtDate")
                        .HasColumnType("int");

                    b.Property<int>("LastEdited")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimePassed")
                        .HasColumnType("int");

                    b.Property<int?>("WorkTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtDate = 81453,
                            CreatedById = 2,
                            DeadlineDate = 81473,
                            Description = "Build a pod for the rocket to start",
                            LastEdited = 81453,
                            Name = "Build a starting pod",
                            Priority = 3,
                            ProjectId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtDate = 81453,
                            CreatedById = 2,
                            DeadlineDate = 81488,
                            Description = "Build a rocket to take the shuttle outside the atmosphere",
                            LastEdited = 81453,
                            Name = "Build a rocket",
                            Priority = 2,
                            ProjectId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ProjectManagementApi.Models.JobEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EndedAtDate")
                        .HasColumnType("int");

                    b.Property<int?>("EndedAtTime")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("StartedAtDate")
                        .HasColumnType("int");

                    b.Property<int>("StartedAtTime")
                        .HasColumnType("int");

                    b.Property<int?>("TimePassed")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("JobEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobId = 1,
                            StartedAtDate = 81453,
                            StartedAtTime = 176776,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            JobId = 2,
                            StartedAtDate = 81453,
                            StartedAtTime = 176776,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ProjectManagementApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedAtDate")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineDate")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndedAtDate")
                        .HasColumnType("int");

                    b.Property<int>("LastEdited")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimePassed")
                        .HasColumnType("int");

                    b.Property<int?>("WorkTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtDate = 81453,
                            CreatedById = 2,
                            DeadlineDate = 81553,
                            Description = "Building a spaceship that will get us to Mars",
                            LastEdited = 81453,
                            Name = "Spaceship to Mars",
                            Priority = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ProjectManagementApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedAtDate")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastEdited")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "",
                            CreatedAtDate = 81453,
                            FirstName = "Rick",
                            LastEdited = 81453,
                            LastName = "Sanchez",
                            Login = "sancheezium",
                            Password = "1234",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "",
                            CreatedAtDate = 81453,
                            FirstName = "Morty",
                            LastEdited = 81453,
                            LastName = "Smith",
                            Login = "morty",
                            Password = "1234",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "",
                            CreatedAtDate = 81453,
                            FirstName = "Summer",
                            LastEdited = 81453,
                            LastName = "Smith",
                            Login = "sumsum",
                            Password = "1234",
                            UserType = 2
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "",
                            CreatedAtDate = 81453,
                            FirstName = "Bird",
                            LastEdited = 81453,
                            LastName = "Person",
                            Login = "bird_person",
                            Password = "birb",
                            UserType = 2
                        });
                });

            modelBuilder.Entity("ProjectManagementApi.Models.Job", b =>
                {
                    b.HasOne("ProjectManagementApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectManagementApi.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagementApi.Models.JobEntry", b =>
                {
                    b.HasOne("ProjectManagementApi.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagementApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectManagementApi.Models.Project", b =>
                {
                    b.HasOne("ProjectManagementApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ProjectManagementApi.Models.User", b =>
                {
                    b.HasOne("ProjectManagementApi.Models.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
